#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$ROOT_DIR/.env"
ENV_EXAMPLE="$ROOT_DIR/.env.example"
APP_NAME="dlmm-exit-bot"

prompt() {
  local label="$1"
  local default="${2:-}"
  local secret="${3:-false}"
  local value=""

  if [[ "$secret" == "true" ]]; then
    if [[ -n "$default" ]]; then
      read -r -s -p "$label [$default]: " value
    else
      read -r -s -p "$label: " value
    fi
    echo
  else
    if [[ -n "$default" ]]; then
      read -r -p "$label [$default]: " value
    else
      read -r -p "$label: " value
    fi
  fi

  if [[ -z "$value" ]]; then
    value="$default"
  fi

  printf '%s' "$value"
}

require_cmd() {
  local cmd="$1"
  local help_msg="$2"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Error: '$cmd' tidak ditemukan. $help_msg"
    exit 1
  fi
}

echo "== DLMM Exit Bot Installer =="
echo

require_cmd node "Install Node.js 18+ dulu, lalu jalankan installer ini lagi."
require_cmd npm "Install npm dulu, lalu jalankan installer ini lagi."

NODE_MAJOR="$(node -p "process.versions.node.split('.')[0]")"
if [[ "$NODE_MAJOR" -lt 18 ]]; then
  echo "Error: Node.js 18+ diperlukan. Versi sekarang: $(node -v)"
  exit 1
fi

if [[ ! -f "$ENV_EXAMPLE" ]]; then
  echo "Error: .env.example tidak ditemukan di $ROOT_DIR"
  exit 1
fi

echo "Project directory: $ROOT_DIR"
echo
echo "Installer ini akan:"
echo "1. Mengisi file .env"
echo "2. Install dependency npm"
echo "3. Install pm2 jika belum ada"
echo "4. Menjalankan bot via pm2"
echo

WALLET_PRIVATE_KEY="$(prompt "WALLET_PRIVATE_KEY (base58)" "" true)"
RPC_URL="$(prompt "RPC_URL" "")"
HELIUS_API_KEY="$(prompt "HELIUS_API_KEY" "" true)"
DRY_RUN="$(prompt "DRY_RUN" "true")"
TIMEZONE="$(prompt "TIMEZONE" "Asia/Jakarta")"
TIMEFRAME="$(prompt "TIMEFRAME" "1H")"
CANDLE_SOURCE="$(prompt "CANDLE_SOURCE (meteora/birdeye)" "meteora")"
POLL_INTERVAL_MINUTES="$(prompt "POLL_INTERVAL_MINUTES" "5")"
EXIT_SWAP_TO_SOL="$(prompt "EXIT_SWAP_TO_SOL" "true")"
TELEGRAM_BOT_TOKEN="$(prompt "TELEGRAM_BOT_TOKEN (optional, enter untuk kosong)" "" true)"
TELEGRAM_CHAT_ID="$(prompt "TELEGRAM_CHAT_ID (optional, enter untuk kosong)" "")"
BIRDEYE_API_KEY="$(prompt "BIRDEYE_API_KEY (optional, enter untuk kosong)" "" true)"
JUPITER_API_KEY="$(prompt "JUPITER_API_KEY (optional, enter untuk kosong)" "" true)"

if [[ -z "$WALLET_PRIVATE_KEY" || -z "$RPC_URL" || -z "$HELIUS_API_KEY" ]]; then
  echo "Error: WALLET_PRIVATE_KEY, RPC_URL, dan HELIUS_API_KEY wajib diisi."
  exit 1
fi

cat > "$ENV_FILE" <<EOF
# Generated by install.sh
WALLET_PRIVATE_KEY=$WALLET_PRIVATE_KEY
RPC_URL=$RPC_URL
HELIUS_API_KEY=$HELIUS_API_KEY

TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID
TELEGRAM_NOTIFY_STARTUP=true
TELEGRAM_NOTIFY_HOLD=false
TELEGRAM_NOTIFY_ERRORS=true
TELEGRAM_TIMEOUT_MS=15000
TELEGRAM_RETRY_COUNT=1

DRY_RUN=$DRY_RUN
LOG_LEVEL=info
TIMEZONE=$TIMEZONE
POLL_INTERVAL_MINUTES=$POLL_INTERVAL_MINUTES

TIMEFRAME=$TIMEFRAME
CANDLE_SOURCE=$CANDLE_SOURCE
BB_TOUCH_RULE=high_gte_upper_band
MACD_GREEN_RULE=first_histogram_red_to_green
EXIT_CLOSE_FULL=true
EXIT_SWAP_TO_SOL=$EXIT_SWAP_TO_SOL

BB_PERIOD=20
BB_STDDEV=2
RSI_PERIOD=2
RSI_EXIT_THRESHOLD=90
MACD_FAST=12
MACD_SLOW=26
MACD_SIGNAL=9

BIRDEYE_API_KEY=$BIRDEYE_API_KEY
JUPITER_API_KEY=$JUPITER_API_KEY
EOF

echo
echo "File .env berhasil dibuat."

cd "$ROOT_DIR"

echo
echo "Installing npm dependencies..."
npm install

if ! command -v pm2 >/dev/null 2>&1; then
  echo
  echo "pm2 belum ada. Installing pm2 globally..."
  npm install -g pm2
fi

echo
echo "Restarting pm2 app: $APP_NAME"
pm2 delete "$APP_NAME" >/dev/null 2>&1 || true
pm2 start "$ROOT_DIR/src/index.js" --name "$APP_NAME"
pm2 save

echo
echo "Install selesai."
echo
echo "Perintah berguna:"
echo "  pm2 status"
echo "  pm2 logs $APP_NAME"
echo "  pm2 restart $APP_NAME"
echo "  pm2 stop $APP_NAME"
echo
echo "Catatan:"
echo "- Saat ini DRY_RUN=$DRY_RUN"
echo "- Jika ingin live mode, ubah DRY_RUN=false di $ENV_FILE lalu jalankan: pm2 restart $APP_NAME"
